Policy Server initial implementation
OceanProtocolEnterprise/policy-server pull request #2
Opened 2024-11-25 08:42 UTC by h0pefu1

Changes in PR 

- initialize action implementation (walt.id)
- download action implementation (walt.id)
- credentialParser for new DDO

@alexei-goncear

2024-11-25 13:12 UTC, alexei-goncear commented
**initialize action implementation (walt.id)** - src/handlers/waltid/actions/initializeHandler.ts (parse credentials from new DDO and calls walt.id /verify endpoint)
**download action implementation (walt.id)** - src/handlers/waltid/actions/downloadHandler.ts (calls walt.id /session endpoint)

2024-11-26 16:15 UTC, alexei-goncear commented
## Initialize

### PolicyServer Endpoint Example
**Endpoint**: `http://localhost:3000/`

### PolicyServer Expected Payload Example
```json
{
  "action": "initialize",
  "documentId": "did:op:123",
  "ddo": {
    "credentialSubject": {
      "credentials": [
        {
          "allow": [
            {
              "vpPolicies": [
                "signature",
                "expired"
              ],
              "vcPolicies": [
                "signature",
                "expired"
              ],
              "requestCredentials": [
                {
                  "type": "VerifiableId",
                  "format": "jwt_vc_json"
                },
                {
                  "type": "ProofOfResidence",
                  "format": "jwt_vc_json"
                },
                {
                  "type": "OpenBadgeCredential",
                  "format": "jwt_vc_json",
                  "policies": [
                    "signature",
                    {
                      "policy": "webhook",
                      "args": "https://example.org/abc/xyz"
                    }
                  ]
                }
              ]
            }
          ]
        }
      ],
      "services": [
        {
          "credentials": [
            {
              "allow": [
                {
                  "vpPolicies": [
                    "signature",
                    "expired"
                  ],
                  "vcPolicies": [
                    "signature",
                    "expired"
                  ],
                  "requestCredentials": [
                    {
                      "type": "VerifiableId",
                      "format": "jwt_vc_json"
                    },
                    {
                      "type": "ProofOfResidence",
                      "format": "jwt_vc_json"
                    },
                    {
                      "type": "OpenBadgeCredential",
                      "format": "jwt_vc_json",
                      "policies": [
                        "signature",
                        {
                          "policy": "webhook",
                          "args": "https://example.org/abc/xyz"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  },
  "serviceId": "0x123",
  "consumerAddress": "0x123",
  "policyServer": {}
}

```


### Walt.Id Endpoint Example
**Endpoint**: `https://verifier.portal.walt.id/verify/`

### Walt.Id Params
**StateId**: `Is generated by PolicyServer and represents the session id, included in response.`
```stateId: randomUUID()```

Policy Server will always add default VP and VC policies, if they are specified in ENV.  (revoked_status_list is this case)

### Walt.Id Payload Example Generated by PolicyServer
```json
{
  "vp_policies": [
    "expired",
    "signature",
    "revoked_status_list"
  ],
  "vc_policies": [
    "expired",
    "signature",
    "revoked_status_list"
  ],
  "request_credentials": [
    {
      "type": "VerifiableId",
      "format": "jwt_vc_json"
    },
    {
      "type": "ProofOfResidence",
      "format": "jwt_vc_json"
    },
    {
      "type": "OpenBadgeCredential",
      "format": "jwt_vc_json",
      "policies": [
        "signature",
        {
          "policy": "webhook",
          "args": "https://example.org/abc/xyz"
        }
      ]
    }
  ]
}

```

### Walt.Id Response Example
```json
"openid4vp://authorize?response_type=vp_token&client_id=https%3A%2F%2Fverifier.portal.walt.id%2Fopenid4vc%2Fverify&response_mode=direct_post&state=ec64a21c-3d81-44f9-8b1d-099c1ec0c7b6&presentation_definition_uri=https%3A%2F%2Fverifier.portal.walt.id%2Fopenid4vc%2Fpd%2Fec64a21c-3d81-44f9-8b1d-099c1ec0c7b6&client_id_scheme=redirect_uri&client_metadata=%7B%22authorization_encrypted_response_alg%22%3A%22ECDH-ES%22%2C%22authorization_encrypted_response_enc%22%3A%22A256GCM%22%7D&nonce=a6a70049-c347-4046-89db-7090b43c858f&response_uri=https%3A%2F%2Fverifier.portal.walt.id%2Fopenid4vc%2Fverify%2Fec64a21c-3d81-44f9-8b1d-099c1ec0c7b6"
```


### PolicyServer Response Example
```json
{
  "success": true,
  "message": "openid4vp://authorize?response_type=vp_token&client_id=https%3A%2F%2Fverifier.portal.walt.id%2Fopenid4vc%2Fverify&response_mode=direct_post&state=ec64a21c-3d81-44f9-8b1d-099c1ec0c7b6&presentation_definition_uri=https%3A%2F%2Fverifier.portal.walt.id%2Fopenid4vc%2Fpd%2Fec64a21c-3d81-44f9-8b1d-099c1ec0c7b6&client_id_scheme=redirect_uri&client_metadata=%7B%22authorization_encrypted_response_alg%22%3A%22ECDH-ES%22%2C%22authorization_encrypted_response_enc%22%3A%22A256GCM%22%7D&nonce=a6a70049-c347-4046-89db-7090b43c858f&response_uri=https%3A%2F%2Fverifier.portal.walt.id%2Fopenid4vc%2Fverify%2Fec64a21c-3d81-44f9-8b1d-099c1ec0c7b6",
  "httpStatus": 200
}

```
In this case `state=ec64a21c-3d81-44f9-8b1d-099c1ec0c7b6` represents Session Id.


## Download

### PolicyServer Endpoint Example
**Endpoint**: `http://localhost:3000/`

### PolicyServer Expected Payload Example
```json
{
  "action": "download",
  "documentId": "did:op:123",
  "ddo": {},
  "serviceId": "0x123",
  "fileIndex": 1,
  "transferTxId": "0x123",
  "consumerAddress": "0x123",
  "policyServer": {
    "sessionId": "ec64a21c-3d81-44f9-8b1d-099c1ec0c7b6"
  }
}
```

### Walt.Id Endpoint Example
**Endpoint**: `https://verifier.portal.walt.id/session/{id}`

**In this example**: `"https://verifier.portal.walt.id/session/{ec64a21c-3d81-44f9-8b1d-099c1ec0c7b6"`.

### Walt.Id Response Example
```json
{
    "id": "ec64a21c-3d81-44f9-8b1d-099c1ec0c7b6",
    "presentationDefinition": {
      "id": "gX1BsdjdwtCm",
      "input_descriptors": [
        {
          "id": "VerifiableId",
          "format": {
            "jwt_vc_json": {
              "alg": [
                "EdDSA"
              ]
            }
          },
          "constraints": {
            "fields": [
              {
                "path": [
                  "$.type"
                ],
                "filter": {
                  "type": "string",
                  "pattern": "VerifiableId"
                }
              }
            ]
          }
        },
        {
          "id": "ProofOfResidence",
          "format": {
            "jwt_vc_json": {
              "alg": [
                "EdDSA"
              ]
            }
          },
          "constraints": {
            "fields": [
              {
                "path": [
                  "$.type"
                ],
                "filter": {
                  "type": "string",
                  "pattern": "ProofOfResidence"
                }
              }
            ]
          }
        },
        {
          "id": "OpenBadgeCredential",
          "format": {
            "jwt_vc_json": {
              "alg": [
                "EdDSA"
              ]
            }
          },
          "constraints": {
            "fields": [
              {
                "path": [
                  "$.type"
                ],
                "filter": {
                  "type": "string",
                  "pattern": "OpenBadgeCredential"
                }
              }
            ]
          }
        }
      ],
      "customParameters": {}
    },
    "customParameters": {}
  },
```


### PolicyServer Response Example
```json
{
  "success": true,
  "message": {
    "id": "ec64a21c-3d81-44f9-8b1d-099c1ec0c7b6",
    "presentationDefinition": {
      "id": "gX1BsdjdwtCm",
      "input_descriptors": [
        {
          "id": "VerifiableId",
          "format": {
            "jwt_vc_json": {
              "alg": [
                "EdDSA"
              ]
            }
          },
          "constraints": {
            "fields": [
              {
                "path": [
                  "$.type"
                ],
                "filter": {
                  "type": "string",
                  "pattern": "VerifiableId"
     [...]

2024-12-04 05:10 UTC, alexcos20 requested changes
Wait.  This is way to overengineered and heavy.

1. Why do we need "by the book approach" with controller, services, etc when we have just one endpoint ?

2. For auth types, we should take a factory class approach, so we don't need to repeat same code

2024-12-17 07:54 UTC, alexcos20 approved these changes

2025-01-02 10:35 UTC, merged